language: node_js

node_js:
  - node

branches:
  only:
  - master

before_script:
  - yarn global add firebase-tools
  - yarn global add @angular/cli

script:
  - echo "Instantiating Tests..."
  - yarn lint
  - yarn build
  - echo "Launching Deploy to Firebase( sastrayonitvat-dev.firebaseapp.com ) now..."

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change

cache:
  yarn: true
  directories:
    - node_modules
